name: Build and Run Tests by Bazel
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - master
      - develop
      - bazel
      - add-retry-mechanism

permissions:
  actions: write
  contents: write

jobs:
  build:
    name: "bazel-compile (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: bazel build --config=remote //...
      - name: Run Tests
        run: bazel test --config=remote //...
      - name: Retry if failed
        # if it failed , retry 2 times at most
        if: failure() && fromJSON(github.run_attempt) < 3
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Attempting to retry workflow..."
          gh workflow run rerun-workflow.yml -F run_id=${{ github.run_id }}